name: Dev Build

on:
  push:
    branches: [ "2.0" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 8
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'

      - name: "Get Information"
        run: |
          echo "VERSIONID=$(cat "gradle.properties" | grep version | cut -d '=' -f 2)" >> $GITHUB_ENV
      - name: Build with Gradle
        run: |
          ./gradlew build

      - name: Upload Console Software
        uses: actions/upload-artifact@v2.2.4
        with:
          name: Build
          path: Applications/Console/build/libs/ResourcePackConverter-Console-${{ env.VERSIONID }}.jar
          retention-days: 40

      - name: Upload GUI Software
        uses: actions/upload-artifact@v2.2.4
        with:
          name: Build
          path: Applications/Gui/build/libs/ResourcePackConverter-Gui-${{ env.VERSIONID }}.jar
          retention-days: 40


